--create database customer
--use customer
SELECT TOP 20 *
FROM cleaned_data;


--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from cleaned_data
group by gender


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from cleaned_data 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from cleaned_data)


-- Q3. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased, round(AVG(review_rating),2) as rating
from cleaned_data
group by item_purchased
order by rating desc


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, avg(purchase_amount) from cleaned_data
where shipping_type in ('Express','Standard')
group by shipping_type


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM cleaned_data
GROUP BY subscription_status


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT top 5 item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM cleaned_data
GROUP BY item_purchased
ORDER BY discount_rate DESC


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM cleaned_data)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;


--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM cleaned_data
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM cleaned_data
WHERE previous_purchases > 5
GROUP BY subscription_status;


--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM cleaned_data
GROUP BY age_group
ORDER BY total_revenue desc;

































































































































































